

# Project Euler: 45
"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

import time

def euler_45(inf):

  # Inversas: (Numeros: x,y,z)
  """
  x = (-1+(1+4*(3*(y**2)-y))**0.5)/2
  z = (2+(4+16*(3*(y**2)-y))**0.5)/8
  """
  listo = True
  y = inf

  while listo:
    x = ecuacion_x(y)
    z = ecuacion_z(y)
    if x == int(x) and z == int(z):
      break
    y+=1

  return ecuacion_final(y)


def ecuacion_final(n):
  return n*(3*n-1)/2


def ecuacion_x(y):
  return (-1+(1+4*(3*(y**2)-y))**0.5)/2

def ecuacion_z(y):
  return (2+(4+16*(3*(y**2)-y))**0.5)/8


##############################################

if __name__ == "__main__":
  
  start = time.time()

  inf = 166

  num = euler_45(inf)

  print("El valor es: {}".format(num))


  print("\nTiempo de operación:",time.time()-start, "seg.")
    
##############################################

"""
El valor es: 1533776805.0

Tiempo de operación: 0.24441766738891602 seg.
"""

